"""empty message

Revision ID: 0dfe179ee26c
Revises: b18b67e412be
Create Date: 2023-09-11 16:29:36.508748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfe179ee26c'
down_revision = 'b18b67e412be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_constraint('uq_owners_username', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.create_unique_constraint('uq_owners_username', ['username'])

    # ### end Alembic commands ###
