"""empty message

Revision ID: 1ff181210213
Revises: 5d8fb57ec49d
Create Date: 2023-09-12 21:57:20.107689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff181210213'
down_revision = '5d8fb57ec49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_author_id_users', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_posts_author_id_users', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###
