"""empty message

Revision ID: 9363b4919ce1
Revises: d887da1feb2b
Create Date: 2023-09-12 22:30:20.331122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9363b4919ce1'
down_revision = 'd887da1feb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_messages_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_author_id_users'), 'users', ['author_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_threads_author_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_threads_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_threads_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_threads_author_id_users', 'users', ['author_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_messages_author_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
